# Generated by Django 2.0.4 on 2018-05-18 17:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Participante',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200, verbose_name='Nome')),
                ('jogo', models.CharField(choices=[('LOL', 'League of Legends'), ('FIFA', 'FIFA'), ('CSGO', 'CS:GO')], max_length=4, verbose_name='Jogo')),
                ('vitoria', models.IntegerField(default=0, verbose_name='Vitorias')),
                ('derrota', models.IntegerField(default=0, verbose_name='Derrotas')),
                ('empate', models.IntegerField(default=0, verbose_name='Empates')),
            ],
        ),
        migrations.CreateModel(
            name='Partida',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jogo', models.CharField(choices=[('LOL', 'League of Legends'), ('FIFA', 'FIFA'), ('CSGO', 'CS:GO')], max_length=4, verbose_name='Jogo')),
                ('dia', models.CharField(choices=[('T', 'Terça-feira'), ('Q', 'Quarta-feira'), ('QI', 'Quinta-feira'), ('S', 'Sexta-feira')], max_length=2, verbose_name='Dia')),
                ('participante_casa', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='participante_casa', to='participante.Participante')),
                ('participante_desafiante', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='participante_desafiante', to='participante.Participante')),
            ],
        ),
    ]
