# Generated by Django 2.0.4 on 2018-05-22 02:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('participante', '0002_partida_vencedor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='partida',
            name='vencedor',
            field=models.CharField(choices=[('C', 'Participante Casa'), ('D', 'Participante Desafiante'), ('E', 'Empate')], max_length=1, verbose_name='Vencedor'),
        ),
    ]
